Repository brainhackorg/brainhack_jupyter_book, pull requests merged in 2021-02, with the labels that each got.

#7 add clean data csv with all brainhack events from the first in 2012…
  brainhack_book/geographical_distribution.ipynb
  data/bhg_sites_test.csv
  data/brainhack-timeline.csv
Labels: documentation, enhancement

#30 Update preprint figure
  brainhack_book/static/preprint_figure-1.png
Labels: preprint

#29 Add landing page text and first interactive figure
  .github/ISSUE_TEMPLATE/question.md
  brainhack_book/_toc.yml
  brainhack_book/evolution_of_brainhack.ipynb
  brainhack_book/index.md
Labels: preprint

#31 Add text to Overview page
  brainhack_book/overview.md
  brainhack_book/preprint_manuscript.md
Labels: preprint

#36 Links and assets test
  .github/workflows/book.yml
  .gitignore
  Makefile
  brainhack_book/preprint_manuscript.md
  brainhack_book/tests/traverse_pages.py
  environment.yml
Labels: enhancement, preprint

#28 ENH/NF affiliation table clearner for author list in paper
  Makefile
  data/affiliations_curated.tsv
  data/authors_affiliations.tsv
  data/coreteam_ranking.tsv
  scripts/mdtable.py
  scripts/neuroview_affiliations_organizer.sh
  scripts/neuroview_author_ranking.py
Labels: preprint

#37 Update locations based on geocoding
  data/brainhack-timeline.csv
Labels: enhancement

#21 Update glossary with new terms
  brainhack_book/glossary.md
Labels: content, enhancement
